apiVersion: v1
kind: Service
metadata:
  name: artemis-service

spec:
  selector:
    app: activemq-artemis

  ports:
  - name: "http"
    port: 8161
    nodePort: 30161

  - name: "core"
    port: 61616
    nodePort: 30616

  - name: "amqp"
    port: 5672
    nodePort: 30672
  type: NodePort